# Generated by Django 6.0.5 on 2026-05-20 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0003_grammarpracticesession_grammarexerciseattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarCoachEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('corrected_sentence', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('cefr_level', models.CharField(blank=True, max_length=2)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('explanation', models.TextField(blank=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'grammar coach entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
