# Generated by Django 6.0.5 on 2026-05-22 16:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0006_round_out_initial_exercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammarcoachentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('grammar_coach', 'Grammar Coach'), ('word_enrichment', 'Word Enrichment')], max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='grammar_aiu_created_d51312_idx'), models.Index(fields=['user', 'feature', 'created_at'], name='grammar_aiu_user_id_49a319_idx')],
            },
        ),
    ]
